version: '3.1'
services:
  stats-server:
    build: ./ewm-stat-service/stat-server
    image: ewm-stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=statdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=statdb
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: statdb
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  #ewm-service:
  #  ports:
  #    - "8080:8080"
  #  environment:
  #    - STAT_SERVER_URL=http://server:9090

  #ewm-db:
  #  image: postgres:14-alpine
