version: '3.1'
services:
  stat-server:
    build: ./ewm-stat-service/stat-server
    image: ewm-stat-service
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/statdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: ./ewm-main-service/main-server
    image: ewm-main-service
    container_name: main-server
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - STAT_SERVER_URL=http://stat-server:9090
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://main-db:5433/maindb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6544:5433"
    volumes:
      - /var/lib/postgresql/data/
    command: -p 5433
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
