CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE compilation_events
(
    compilation_entity_id BIGINT NOT NULL,
    events_id             BIGINT NOT NULL
);

CREATE TABLE event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    annotation         VARCHAR(255)                            NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255)                            NOT NULL,
    event_date         VARCHAR(255)                            NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                 NOT NULL,
    state              VARCHAR(255)                            NOT NULL,
    title              VARCHAR(255),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE request
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    event_id BIGINT,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE compilation_events
    ADD CONSTRAINT uc_compilation_events_events UNIQUE (events_id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES "user" (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_LOCATION FOREIGN KEY (location_id) REFERENCES location (id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_compilation_entity FOREIGN KEY (compilation_entity_id) REFERENCES compilation (id);

ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_event_entity FOREIGN KEY (events_id) REFERENCES event (id);