logging:
  level:
    org:
      springframework:
        orm:
          jpa: WARN
          jpa.JpaTransactionManager: WARN
        transaction: WARN
        transaction.interceptor: WARN
    ru:
      practicum:
        mainserver: DEBUG
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6544/maindb
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create