logging:
  level:
    org:
      springframework:
        orm:
          jpa: WARN
          jpa.JpaTransactionManager: WARN
        transaction: WARN
        transaction.interceptor: WARN
    ru:
      practicum:
        statserver: DEBUG
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/stat
    username: test
    password: test

  h2:
    console:
      enabled: true


  jpa:
    show-sql: true